#ifndef _ENUMS_H_
#define _ENUMS_H_

enum CHARACTER_IMAGES {
    CHAR_NONE = -1,
    CHAR_NONE_2 = 0,
    CHAR_KOOPA_RED = 1,
    CHAR_KOOPA_GREEN = 2,
    CHAR_TOAD = 3,
    CHAR_BOWSER = 4,
    CHAR_BABY_BOWSER = 5,
    CHAR_GOOMBA = 6,
    CHAR_BOO = 7,
    CHAR_STEAMER = 8,
    CHAR_SKELETON_KEY = 9,
    CHAR_PICKER = 10,
    CHAR_MUSHROOM = 11,
    CHAR_GOLDEN_MUSHROOM = 12,
    CHAR_PLUNDER_CHEST = 13,
    CHAR_BOWSER_BOMB = 14,
    CHAR_DUELING_GLOVE = 15,
    CHAR_WARP_BLOCK = 16,
    CHAR_BOO_BELL = 17,
    CHAR_BOWSER_SUIT = 18,
    CHAR_MAGIC_LAMP = 19,
    CHAR_SKELETON_KEY_TRANS_BACKGROUND = 20,
    CHAR_PICKER_TRANS_BACKGROUND = 21,
    CHAR_WIGGLER = 22,
    CHAR_SUSHI = 23,
    CHAR_THOWMP = 24,
    CHAR_SNUFIT = 25,
    CHAR_BOWSER_WESTERN = 26,
    CHAR_BOWSER_PIRATE = 27,
    CHAR_SHY_GUY = 28,
    CHAR_BOB_OMB_BUDDY = 29,
    CHAR_BOWSER_SPACE = 30,
    CHAR_BABY_BOWSER_BANKER = 31, // in bowser land bank
    CHAR_BABY_BOWSER_SHOPKEEPER = 32, //in bowser land shop
    CHAR_METALLIC_BLOOPER = 33,
    CHAR_KAMEK = 34,
    CHAR_BOWSER_MYSTERY = 35,
    CHAR_BOWSER_HORROR = 36,
    CHAR_BOWSER_BOWSER = 37, //bowser land image
    CHAR_MR_I = 38,
    CHAR_WHOMP = 39,
    CHAR_BIG_BOO = 40,
    CHAR_BATTLE_T = 41,
};

#endif //_ENUMS_H_